- send2cgeo.user.js
Fix layour in new search results on gc.com
> Release version 0.34

- send2cgeoOc.user.js
Enable script on the https site of OC
> enable https for OC

- send2cgeo.user.js
> Fix premium search page

- send2cgeo.user.js
> Fix column header place for premium

- send2cgeo.user.js
- send2cgeoOc.user.js
Fixes #36 
Merging this, will set v0.40 live to the users. Please do not merge yet.
Let us wait for test results of @KeyWeeUsr and @BMWHoizer
> New release V0.40

- send2cgeo.user.js
Hello,
I have found out, that on send2.cgeo.org the URL goes to release branch. Could you please then merge master to release so the update I did becomes available to normal users?
Thanks,
TriakCZ
> Please merge master to release

- send2cgeoOcPl.user.js
The default site are now
- https://opencaching.pl
- https://www.opencaching.nl
> Add https to the websites list (pl, nl)

- send2cgeo.user.js
> add jquery to let the script run after latest FF update

- send2cgeo.user.js
> injection in list view with doubled icon

- send2cgeo.user.js
- Indentation 4, spaces, brackets, comments etc. configured
- renamed second "var html" to html2
- remove unneeded line (only for history reasons in the code)
$('#Download p:last').append(html);
> code formatting

- send2cgeo.user.js
The initialization of "map" is now back.
Thanks to @capoaira
> "map" no more resolved

- send2cgeo.user.js
> support seachmap

- send2cgeo.user.js
> s2cgeo does't work on recentlyviewed and nearest list

- send2cgeo.user.js
The button is shown because waitForKeyElements() find new Elements after logging and a Cache
fix #85
> s2cg button after loging a cache

- send2cgeo.user.js
I made these changes to make the code clearer and shorter.
The IDs are not a safe way, sometimes GS changes them.
> use .href.match()

- send2cgeo.user.js
fix #68 
- Now the s2cgeo button will be insert in every language.
- Changed the s2cgeo button img to the s2cgeo icon.
> send2cgeo only works in english on the browsemap

- send2cgeo.user.js
- Show cursor pointer
- Changed the s2cgeo button img to the s2cgeo icon.
https://github.com/cgeo/send2cgeo/issues/81#issuecomment-581873912
> Fit on the cache detail button to rest of the script.

- send2cgeo.user.js
- send2cgeoOc.user.js
- send2cgeoOcPl.user.js
- Include the script for opencaching.de into the GS script (fix #3)
- Remove Oc and OcPl script (fix #45)
- Changed the s2cgeo button img to the s2cgeo icon.
I don't know if these changes are still in demand. You can look at it and decide whether it fits or not.
If this should take longer, in my opinion it should not necessarily be in the next release.
> Combine send2cgeo scripts into one script

- send2cgeo.user.js
> s2cg on recentlyviewedcaches does not work correct with GClh

- send2cgeo.user.js
- support new list page
- tabs zu spaces
fix #69
> support new list page

- send2cgeo.user.js
#69, #14
- send selected on BML
- helper function removeIfAlreadyExists
- tabs to spaces
> Send multiple caches on BML

- send2cgeo.user.js
> Add owner dashboard

- send2cgeo.user.js
fix #117
@Lineflyer, @bekuno 
can you have a look at this?
> s2cg button doesn't appear immediately on new map

- send2cgeo.user.js
> support oc map

- send2cgeo.user.js
> s2cg button on searchmap popup

- README.md
- Improve description
- Add installation guide
- referencing to Tampermonkey as preferred user script manager (as on the [send2cgeo website](https://www.cgeo.org/send2cgeo.html))
- Fix typo
> optimize README

- send2cgeo.user.js
> Send "Out of the box" as default

- send2cgeo.user.js
> Columns unaligned on COD and BML if website run not in English

- send2cgeo.user.js
> The "Send List" link appears multiple times in new dashboard
